import rtconfig
Import('RTT_ROOT')
from building import *

# get current directory
cwd = GetCurrentDir()

# The set of source files associated with this SConscript file.
src = Split("""
CMSIS/Device/ST/STM32F1xx/Source/Templates/system_stm32f1xx.c
STM32F1xx_HAL_Driver/Src/stm32f1xx_hal_dma.c
STM32F1xx_HAL_Driver/Src/stm32f1xx_hal_cortex.c
STM32F1xx_HAL_Driver/Src/stm32f1xx_hal_crc.c
STM32F1xx_HAL_Driver/Src/stm32f1xx_hal_pwr.c
STM32F1xx_HAL_Driver/Src/stm32f1xx_hal_rcc.c
STM32F1xx_HAL_Driver/Src/stm32f1xx_hal_rcc_ex.c
STM32F1xx_HAL_Driver/Src/stm32f1xx_hal.c
STM32F1xx_HAL_Driver/Src/stm32f1xx_hal_cec.c
STM32F1xx_HAL_Driver/Src/stm32f1xx_hal_gpio.c
""")

src += ['STM32F1xx_HAL_Driver/Src/stm32f1xx_hal_gpio_ex.c']

src += ['STM32F1xx_HAL_Driver/Src/stm32f1xx_hal_uart.c']
src += ['STM32F1xx_HAL_Driver/Src/stm32f1xx_hal_usart.c']

src += ['STM32F1xx_HAL_Driver/Src/stm32f1xx_hal_i2c.c']

src += ['STM32F1xx_HAL_Driver/Src/stm32f1xx_hal_spi.c']
src += ['STM32F1xx_HAL_Driver/Src/stm32f1xx_ll_spi.c']

src += ['STM32F1xx_HAL_Driver/Src/stm32f1xx_hal_pcd.c']
src += ['STM32F1xx_HAL_Driver/Src/stm32f1xx_hal_pcd_ex.c'] 
src += ['STM32F1xx_HAL_Driver/Src/stm32f1xx_ll_usb.c']
src += ['STM32F1xx_HAL_Driver/Src/stm32f1xx_hal_hcd.c']

src += ['STM32F1xx_HAL_Driver/Src/stm32f1xx_hal_can.c']

src += ['STM32F1xx_HAL_Driver/Src/stm32f1xx_hal_tim.c']
src += ['STM32F1xx_HAL_Driver/Src/stm32f1xx_hal_tim_ex.c']

src += ['STM32F1xx_HAL_Driver/Src/stm32f1xx_hal_eth.c']

src += ['STM32F1xx_HAL_Driver/Src/stm32f1xx_hal_adc.c']
src += ['STM32F1xx_HAL_Driver/Src/stm32f1xx_hal_adc_ex.c']

src += ['STM32F1xx_HAL_Driver/Src/stm32f1xx_hal_rtc.c']
src += ['STM32F1xx_HAL_Driver/Src/stm32f1xx_hal_rtc_ex.c']

src += ['STM32F1xx_HAL_Driver/Src/stm32f1xx_hal_iwdg.c']
src += ['STM32F1xx_HAL_Driver/Src/stm32f1xx_hal_wwdg.c']

src += ['STM32F1xx_HAL_Driver/Src/stm32f1xx_ll_sdmmc.c']
src += ['STM32F1xx_HAL_Driver/Src/stm32f1xx_hal_sd.c']

src += ['STM32F1xx_HAL_Driver/Src/stm32f1xx_hal_i2s.c']

src += ['STM32F1xx_HAL_Driver/Src/stm32f1xx_hal_nor.c']

src += ['STM32F1xx_HAL_Driver/Src/stm32f1xx_hal_nand.c']

src += ['STM32F1xx_HAL_Driver/Src/stm32f1xx_ll_fsmc.c']
src += ['STM32F1xx_HAL_Driver/Src/stm32f1xx_hal_sram.c']

src += ['STM32F1xx_HAL_Driver/Src/stm32f1xx_hal_flash.c']
src += ['STM32F1xx_HAL_Driver/Src/stm32f1xx_hal_flash_ex.c']

path = [cwd + '/CMSIS/Device/ST/STM32F1xx/Include', 
    cwd + '/STM32F1xx_HAL_Driver/Inc',
    cwd + '/CMSIS/Include']

CPPDEFINES = ['USE_HAL_DRIVER']
group = DefineGroup('Libraries', src, depend = [''], CPPPATH = path, CPPDEFINES = CPPDEFINES)

Return('group')
